# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/hp/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-22524-DESKTOP-9SQ9M3B/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Physopt 32-662} -limit 9999
set_msg_config -id {Physopt 32-668} -limit 9999
set_msg_config -id {Physopt 32-702} -limit 9999
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hp/Desktop/AES_Project/AES_Vivado/AES_Vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/hp/Desktop/AES_Project/AES_Vivado/AES_Vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/hp/Desktop/AES_Project/AES_Vivado/AES_Vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/hp/Desktop/AES_Project/DFF_128.v
  C:/Users/hp/Desktop/AES_Project/KeyExpansion.v
  C:/Users/hp/Desktop/AES_Project/Sbox.v
  C:/Users/hp/Desktop/AES_Project/mixcolumns.v
  C:/Users/hp/Desktop/AES_Project/roundkey.v
  C:/Users/hp/Desktop/AES_Project/shiftrows.v
  C:/Users/hp/Desktop/AES_Project/subbytes.v
  C:/Users/hp/Desktop/AES_Project/AES_Encryption.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hp/Desktop/AES_Project/AES_Vivado/AES_Vivado.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/hp/Desktop/AES_Project/AES_Vivado/AES_Vivado.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top AES_Encryption -part xc7vx485tffg1157-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AES_Encryption.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AES_Encryption_utilization_synth.rpt -pb AES_Encryption_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
